name: Deploy to AWS using CDK

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras para el despliegue automático

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'  # Ajusta según la versión de .NET que estés usando

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Ajusta según la versión de Node.js que estés usando

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build src/MyCdkApp/MyCdkApp.csproj

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia según la región en la que desees desplegar

    - name: Deploy with CDK
      run: cdk deploy --require-approval never
